build(system_dlkm): update step for monolithic trees
Since we build all the modules at once in monolithic trees which includes modules that goto into vendor_boot
ramdisk, vendor_dlkm & system_dlkm, we need to filter what modules goes into system_dlkm

In mixed tree, we don't have the headache since all the modules built from gki-kernel goes into the
system_dlkm partition.

Therefore like vendor_dlkm & vendor_boot, we implement modules filtering for system_dlkm too.
Also note that since system_dlkm is not flattened we do not copy *.ko directly into DEPMOD_DIR_ROOT,
instead we copy the modules with its relative path from OUT/lib/modules/UNAME

Signed-off-by: nullptr_t <nullptr.oss@gmail.com>

diff --git a/.github/kernel/action.yml b/.github/kernel/action.yml
--- a/.github/kernel/action.yml
+++ b/.github/kernel/action.yml
@@ -1420,6 +1420,9 @@ runs:
         UNAME=$(ls "${OUT}/lib/modules/")
         SYSTEM_DLKM_STAGING_DIR="${OUT}/system_dlkm_staging"
         SYSTEM_DLKM_STAGING_ROOT="${SYSTEM_DLKM_STAGING_DIR}/lib/modules/${UNAME}"
+        # Add for Monolithic Trees
+        DEPMOD_DIR="${SYSTEM_DLKM_STAGING_DIR}"
+        DEPMOD_DIR_ROOT="${SYSTEM_DLKM_STAGING_DIR}/lib/modules/${UNAME}"
 
         if [[ -d "${KERNEL_PLATFORM}/build/build-tools/path" ]]; then
           export PATH="${KERNEL_PLATFORM}/build/build-tools/path/linux-x86:$PATH"
@@ -1437,9 +1440,49 @@ runs:
         # Don't create SYSTEM_DLKM_STAGING_DIR and copy the OUT/lib folder cause it has many unnecessary files
         # Instead create lib and copy modules folder from OUT/lib/modules to SYSTEM_DLKM_STAGING_DIR/lib/
         mkdir -p "${SYSTEM_DLKM_STAGING_DIR}/lib"
-        
+
         # copy modules and other files generated by depmod to staging dir
-        cp -a "${OUT}/lib/modules" "${SYSTEM_DLKM_STAGING_DIR}/lib/"
+        if [[ "${BUILD_TYPE}" == "Mixed Build" ]]; then
+          cp -a "${OUT}/lib/modules" "${SYSTEM_DLKM_STAGING_DIR}/lib/"
+        else
+          # Tbh the implementation below is useless since this step never kicks in monolithic tree builds but
+          # like other changes, I simply mirrored the changes from kernel_modules action
+          #
+          # Since we build all the modules at once in monolithic trees which includes modules that goto into vendor_boot
+          # ramdisk, vendor_dlkm & system_dlkm, we need to filter what modules goes into system_dlkm
+          #
+          # In mixed tree, we don't have the headache since all the modules built from gki-kernel goes into the
+          # system_dlkm partition.
+          if [[ ! -f "${PREBUILTS}/system_dlkm.modules.include ]]; then
+            echo "::error:: system_dlkm.modules.include file is missing"
+            exit 1
+          fi
+
+          # copy modules to DEPMOD_DIR_ROOT
+          # NOTE: do depmod from DEPMOD_DIR
+          cd "${OUT}/lib/modules/${UNAME}"
+          missing_modules=$(mktemp)
+          while IFS= read -r module || [[ -n "${module}" ]]; do
+            module_path=$(find . -name "${module}" -print -quit)
+            if [[ -n "${module_path}" ]]; then
+              cp --parents "${module_path}" "${DEPMOD_DIR_ROOT}"
+            else
+              echo "::warning:: ${module} not found"
+              echo "${module}" >> "${missing_modules}"
+            fi
+          done < "${PREBUILTS}/system_dlkm.modules.include"
+
+          if [[ -s "${missing_modules}" ]]; then
+            echo "::error:: The following system_dlkm modules are missing :"
+            echo "$(cat "${missing_modules}")"
+            echo "Stopping build!"
+            exit 1
+          fi
+
+          cd "${DEPMOD_DIR}"
+          echo "::note:: Performing depmod"
+          depmod -F "${OUT}/System.map" -b . "${UNAME}"
+        fi
 
         if [[ -f "${PREBUILTS}/system_dlkm.modules.load" ]]; then
           cp "${PREBUILTS}/system_dlkm.modules.load" "${SYSTEM_DLKM_STAGING_ROOT}/modules.load"
